INSERT INTO DATA_POS_PATTERNS (pos_pattern) VALUES 
 ('NN VBD NN NNS') , 
 ('PRP VBP') , 
 ('NN VBD DT NN') , 
 ('NN NN NN NN NN') , 
 ('NNS VBP NN') , 
 ('NNS VBP') , 
 ('NN NN DT NN') , 
 ('DT') , 
 ('DT NN NN PRP VBP JJ') , 
 ('NN NN DT') , 
 ('NN') , 
 ('DT NN') , 
 ('NN NN') , 
 ('NN PRP') , 
 ('NN VBD') , 
 ('NN PRP VBP JJ') , 
 ('NN VBD NN DT') , 
 ('NN NN DT NN VBZ') , 
 ('NN VBD NN NN') , 
 ('NN VBD NN') , 
 ('NN VBD DT') , 
 ('NN NN NN NN') , 
 ('PRP') , 
 ('DT NN NN PRP') , 
 ('DT NN NN PRP VBP JJ NN') , 
 ('NN NN NN') , 
 ('NNS') , 
 ('DT NN NN PRP VBP') , 
 ('NN PRP VBP') , 
 ('PRP VBP JJ') , 
 ('DT NN NN');
