INSERT INTO DATA_POS_PATTERNS VALUES ('NN VBD NN DT') , 
 ('NN NN DT NN VBZ') , 
 ('NN VBD NN NN') , 
 ('NN VBD NN') , 
 ('NN VBD NN NNS') , 
 ('PRP VBP') , 
 ('NN VBD DT NN') , 
 ('NN PRP') , 
 ('NN NN NN NN NN') , 
 ('NNS VBP NN') , 
 ('DT NN NN PRP VBP JJ NN') , 
 ('PRP VBP JJ') , 
 ('NN NN NN') , 
 ('NN VBD') , 
 ('NN PRP VBP JJ');