INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Hello                                                                                                                                                                            ', 'hello');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Hi                                                                                                                                                                             ', 'hi');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES (' Hey                                                                                                                                                                             ', 'hey');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Hola                                                                                                                                                                           ', 'hola');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Yo                                                                                                                                                                             ', 'yo');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('How are you?                                                                                                                                                                  ', 'how are you');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("What''s up?                                                                                                                                                           ", 'whats up');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Sup?                                                                                                                                                              ', 'sup');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("How''s it going?                                                                                                                                                          ", 'hows it going');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('How are things?                                                                                                                                                     ', 'how are things');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Not too bad                                                                                                                                                 ', 'not too bad');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Fine.                                            ', 'fine');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Alright                                                                          ', 'alright');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Not much...                                                                                                                    ', 'not much');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Good!', 'good');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Okay                                                                                                                                         ', 'okay');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Hello, how are you?', 'hello how are you');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("I'm okay, thanks for asking!", 'im okay thanks for asking');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("I'm great, thanks for asking!", 'im great thanks for asking');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("I've been better....", 'ive been better');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ("What''s cooking good looking?", 'whats cooking good looking');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Not much, how about you?', 'not much how about you');
INSERT INTO DATA_PHRASES (orig_utterance, sani_utterance) VALUES ('Good, how are you?', 'good how are you');
